package blog.anirbanm.googlehr.model.vo;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 08 17:56:52 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsPVOImpl extends BaseProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsPVOImpl() {
    }

    @Override
    public void executeQuery() {
        setSortBy("DepartmentId");
        super.executeQuery();
    }
}

