package blog.anirbanm.googlehr.model.vo;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 05 01:12:45 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesPVOImpl extends BaseProgrammaticViewObjectImpl {
    
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesPVOImpl() {
    }

    @Override
    public void executeQuery() {
        setSortBy("EmployeeId");
        super.executeQuery();
    }
}

