package blog.anirbanm.googlehr.model.am.common;

import blog.anirbanm.googlehr.viewmodel.data.Department;

import blog.anirbanm.googlehr.viewmodel.data.Employee;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 08 12:04:07 IST 2018
// ---------------------------------------------------------------------
public interface GoogleHrModule extends ApplicationModule {
    void generateAccessToken();

    void initFirebase();

    void onDepartmentSelection();

    void initDepartments();

    void addDepartment(Department department);

    void deleteDepartment();

    void addEmployee(Employee employee);

    void uploadProfileImage(byte[] data);

    String getProfileImage();

    void deleteEmployee();
}

